/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 19:27:36 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.impl2.Magazine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Magazine_ESTest extends Magazine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Magazine magazine0 = new Magazine("", 2000, 0, 0);
      int int0 = magazine0.calculatePenalty(255);
      assertEquals(2, magazine0.getDay());
      assertEquals(3000, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Magazine magazine0 = new Magazine((String) null, 2000, 2000, 1);
      magazine0.year = 1;
      int int0 = magazine0.calculatePenalty(1);
      assertEquals(2000, int0);
      assertEquals(2, magazine0.getDay());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Magazine magazine0 = new Magazine("ir.ramtung.impl2.Magazine", 1390, 1390, 0);
      int int0 = magazine0.calculatePenalty(0);
      assertEquals(3000, int0);
      assertEquals(2, magazine0.getDay());
  }
}
