/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 19:28:45 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.impl2.Book;
import ir.ramtung.impl2.Document;
import ir.ramtung.impl2.Magazine;
import ir.ramtung.impl2.Prof;
import java.util.List;
import java.util.Arrays;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Prof_ESTest extends Prof_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Prof prof0 = new Prof("");
      assertTrue(prof0.canBorrow());
      
      Magazine magazine0 = new Magazine("", 2505, 0, 2505);
      Book book0 = new Book("", 2505);
      List<Document> list0 = Arrays.asList((Document) magazine0, (Document) magazine0, (Document) magazine0, (Document) book0, (Document) book0, (Document) book0, (Document) book0);
      prof0.docsBorrow = list0;
      boolean boolean0 = prof0.canBorrow();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Prof prof0 = new Prof("Tj]8:");
      boolean boolean0 = prof0.canBorrow();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Prof prof0 = new Prof("Tj]8:");
      Magazine magazine0 = new Magazine("Tj]8:", (-1958), (-24), (-1540));
      prof0.borrow(magazine0);
      prof0.borrow(magazine0);
      prof0.borrow(magazine0);
      prof0.borrow(magazine0);
      assertTrue(prof0.canBorrow());
      
      prof0.borrow(magazine0);
      boolean boolean0 = prof0.canBorrow();
      assertFalse(boolean0);
  }
}
