/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 19:28:40 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.impl2.Reference;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Reference_ESTest extends Reference_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Reference reference0 = new Reference("", (-1216));
      int int0 = reference0.calculatePenalty((-1));
      assertEquals(5, reference0.getDay());
      assertEquals(5000, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Reference reference0 = new Reference("", (-1216));
      int int0 = reference0.calculatePenalty((-3));
      assertEquals(5, reference0.getDay());
      assertEquals(5000, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Reference reference0 = new Reference("", (-1748));
      int int0 = reference0.calculatePenalty((-1748));
      assertEquals(5, reference0.getDay());
      assertEquals(7000, int0);
  }
}
