/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 18:26:35 GMT 2024
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl1.Library;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Library_ESTest extends Library_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.addBook("r", 0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Negative or zero copies of a document cannot be added
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Library library0 = new Library();
      library0.timePass(0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.addMagazine("", 1, 0, (-2164));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Documents with empty title are not allowed
         //
         verifyException("ir.ramtung.impl1.Document", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("x", "x");
      library0.addBook("x", 1);
      library0.borrow("x", "x");
      library0.timePass(1);
      library0.extend("x", "x");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("'*EX*!nMN;7", "'*EX*!nMN;7");
      library0.addBook("'*EX*!nMN;7", 1656);
      library0.borrow("'*EX*!nMN;7", "'*EX*!nMN;7");
      library0.timePass(1656);
      int int0 = library0.getTotalPenalty("'*EX*!nMN;7");
      assertEquals(8181000, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.addStudentMember("", "");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Empty member name not allowed
         //
         verifyException("ir.ramtung.impl1.Member", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Library library0 = new Library();
      library0.addBook((String) null, 5261);
      try { 
        library0.addMagazine((String) null, 1111, 1111, 7);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Document with the same title exists
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("'*EX*!nMN;7", "'*EX*!nMN;7");
      try { 
        library0.addProfMember("'*EX*!nMN;7");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Member with the same name exists
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Library library0 = new Library();
      library0.addBook("'*EX*!nMN;7", 1656);
      try { 
        library0.addReference("'*EX*!nMN;7", 1656);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Document with the same title exists
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.addBook((String) null, (-599));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Negative or zero copies of a document cannot be added
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("l0kvQ`o++aeJk7", "l0kvQ`o++aeJk7");
      library0.addStudentMember("l0kvQ`o++aeJk7", "H.d]hK3S~F_.q~)n");
      library0.addBook("H.d]hK3S~F_.q~)n", 4981);
      library0.borrow("l0kvQ`o++aeJk7", "H.d]hK3S~F_.q~)n");
      library0.borrow("H.d]hK3S~F_.q~)n", "H.d]hK3S~F_.q~)n");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("'*EX*!nMN;7", "'*EX*!nMN;7");
      library0.addBook("'*EX*!nMN;7", 1656);
      library0.borrow("'*EX*!nMN;7", "'*EX*!nMN;7");
      try { 
        library0.returnDocument("'*EX*!nMN;7", "");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // The document is not in member's loan
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("'*EX*!nMN;7", "'*EX*!nMN;7");
      library0.addBook("'*EX*!nMN;7", 21);
      library0.borrow("'*EX*!nMN;7", "'*EX*!nMN;7");
      try { 
        library0.returnDocument("p@[&|>;|'p)CT`", "p@[&|>;|'p)CT`");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // The document is not in member's loan
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("'*EX*nN;)FJ", "'*EX*nN;)FJ");
      library0.addProfMember((String) null);
      library0.addBook("'*EX*nN;)FJ", 1);
      library0.borrow("'*EX*nN;)FJ", "'*EX*nN;)FJ");
      int int0 = library0.getTotalPenalty((String) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.timePass((-1083));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot go back in time
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.getTotalPenalty("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot find member
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.extend("\"\"7", "_.OdA\"QSHFE(");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // The document is not in member's loan
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("'*EX*nN;)FJ", "'*EX*nN;)FJ");
      library0.addBook("'*EX*nN;)FJ", 1);
      library0.borrow("'*EX*nN;)FJ", "'*EX*nN;)FJ");
      List<String> list0 = library0.availableTitles();
      assertFalse(list0.contains("'*EX*nN;)FJ"));
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Library library0 = new Library();
      library0.addBook("'*EX*nN;)FJ", 1);
      List<String> list0 = library0.availableTitles();
      assertTrue(list0.contains("'*EX*nN;)FJ"));
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("'*EX*!nMN;7", "'*EX*!nMN;7");
      library0.addBook("'*EX*!nMN;7", 1656);
      library0.borrow("'*EX*!nMN;7", "'*EX*!nMN;7");
      library0.borrow("'*EX*!nMN;7", "'*EX*!nMN;7");
      try { 
        library0.borrow("'*EX*!nMN;7", "'*EX*!nMN;7");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot borrow more documents
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("'*EX*nN;)FJ", "'*EX*nN;)FJ");
      library0.addProfMember((String) null);
      library0.addBook("'*EX*nN;)FJ", 1);
      library0.borrow("'*EX*nN;)FJ", "'*EX*nN;)FJ");
      try { 
        library0.borrow((String) null, "'*EX*nN;)FJ");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Document is not available to borrow
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Library library0 = new Library();
      library0.addBook((String) null, 1);
      try { 
        library0.borrow((String) null, (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot find member to borrow
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.borrow("", "vOQ4$obSk");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot find document to borrow
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("jn{KpUW-PiV/", 540, 540, 540);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("'*EX*!nN;7", "?WU[(G7>FHc@8zoO^2");
      library0.addBook("m*WrFj<S9:Q", 1);
      library0.borrow("?WU[(G7>FHc@8zoO^2", "m*WrFj<S9:Q");
      library0.returnDocument("?WU[(G7>FHc@8zoO^2", "m*WrFj<S9:Q");
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference("Magazine withTzero or negative publication year", 1);
  }
}
