/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 19:26:32 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.impl2.Book;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Book_ESTest extends Book_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Book book0 = new Book("goA&\"F&S", (-20));
      int int0 = book0.calculatePenalty((-21));
      assertEquals(3000, int0);
      assertEquals(10, book0.getDay());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Book book0 = new Book("", (-1));
      int int0 = book0.calculatePenalty((-7));
      assertEquals(10, book0.getDay());
      assertEquals(2000, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Book book0 = new Book("goA&\"F&S", (-20));
      int int0 = book0.calculatePenalty((-393));
      assertEquals(2000, int0);
      assertEquals(10, book0.getDay());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Book book0 = new Book("goA&\"F&S", (-20));
      int int0 = book0.calculatePenalty(3000);
      assertEquals(2000, int0);
      assertEquals(10, book0.getDay());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Book book0 = new Book("?%`/e9,tZ}-5", (-17));
      int int0 = book0.calculatePenalty((-17));
      assertEquals(3000, int0);
      assertEquals(10, book0.getDay());
  }
}
