/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 18:27:46 GMT 2024
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl1.Magazine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Magazine_ESTest extends Magazine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Magazine magazine0 = new Magazine((String) null, 1390, 1390);
      int int0 = magazine0.penaltyFor(3175);
      assertEquals(9525000, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine("N", 107, (-2776));
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative number
         //
         verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine("}:.IYtG-^hfC", (-714), 2200);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative publication year
         //
         verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Magazine magazine0 = new Magazine("AOa", 920, 876);
      int int0 = magazine0.penaltyFor(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Magazine magazine0 = new Magazine("hK]^W5PI)Jjk,zj", 5451, 5451);
      int int0 = magazine0.penaltyFor((-1));
      assertEquals((-3000), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Magazine magazine0 = new Magazine("?g/oHD!=av", 34, 34);
      int int0 = magazine0.penaltyFor(34);
      assertEquals(68000, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine("y8H'qsFP<wmQs7c", 831, 0);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative number
         //
         verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine("iLTc9] m!K//Vs", 0, 0);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative publication year
         //
         verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Magazine magazine0 = new Magazine("hK]^W5PI)Jjk,zj", 5451, 5451);
      int int0 = magazine0.loanDuration();
      assertEquals(2, int0);
  }
}
