/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 18:33:24 GMT 2024
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl1.Member;
import ir.ramtung.impl1.Professor;
import ir.ramtung.impl1.Student;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Member_ESTest extends Member_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Student student0 = new Student("8UE(", "8UE(");
      student0.penalize(2);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Professor professor0 = new Professor("=R(`t-=_41{X$oeoE");
      Student student0 = new Student("=R(`t-=_41{X$oeoE", "px$p|'eO~(h`e");
      boolean boolean0 = professor0.sameAs(student0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Student student0 = new Student(";", ";");
      boolean boolean0 = student0.isNamed(";");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Professor professor0 = new Professor("=R(`t-=_41{X$oeoE");
      professor0.prevPenalty = 321;
      int int0 = professor0.getPrevPenalty();
      assertEquals(321, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Student student0 = new Student("?a9\";vAx", "?a9\";vAx");
      student0.prevPenalty = (-2078);
      int int0 = student0.getPrevPenalty();
      assertEquals((-2078), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Professor professor0 = new Professor("Empty member name not allowed");
      // Undeclared exception!
      try { 
        professor0.sameAs((Member) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ir.ramtung.impl1.Member", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Professor professor0 = null;
      try {
        professor0 = new Professor("");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Empty member name not allowed
         //
         verifyException("ir.ramtung.impl1.Member", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Student student0 = new Student("?a9\";vAx", "?a9\";vAx");
      int int0 = student0.getPrevPenalty();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Student student0 = new Student("?a9\";vAx", "?a9\";vAx");
      boolean boolean0 = student0.sameAs(student0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Professor professor0 = new Professor("Empty member name not allowed");
      boolean boolean0 = professor0.isNamed("");
      assertFalse(boolean0);
  }
}
